# Generated by Django 2.0.7 on 2018-09-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, '操作系统'), (2, '监控'), (3, '编程'), (4, 'Web前端'), (5, '数据库技术'), (6, '大数据'), (7, '云计算')], default=None),
        ),
    ]
