# Generated by Django 2.0.7 on 2018-09-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180917_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='春暖花开', max_length=64, verbose_name='个人博客标题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/imgs', verbose_name='头像'),
        ),
    ]
