# Generated by Django 2.0.6 on 2018-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='f',
            field=models.FileField(default='tttttt', upload_to=''),
            preserve_default=False,
        ),
    ]
