# Generated by Django 2.0.6 on 2018-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfor_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfor',
            name='f',
        ),
        migrations.AddField(
            model_name='userinfor',
            name='ctime',
            field=models.DateTimeField(null=True),
        ),
    ]
