# Generated by Django 2.0.6 on 2018-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180718_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='color',
            field=models.IntegerField(choices=[(1, '黑色'), (2, '白色'), (3, '蓝色')], default=1),
            preserve_default=False,
        ),
    ]
