# Generated by Django 2.0.6 on 2018-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180718_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='email',
            field=models.EmailField(blank=True, default='1111', max_length=254, null=True, unique=True),
        ),
    ]
