# Generated by Django 2.0.6 on 2018-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180718_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
