# Generated by Django 2.0.6 on 2018-07-17 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180718_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='test',
            field=models.CharField(error_messages={'c1': '有限错误信息1'}, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='c1', message='错误了', regex='root_\\d+')]),
        ),
    ]
