# Generated by Django 2.0.6 on 2018-07-17 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_userinfor_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='test',
            field=models.CharField(default='eeeee', error_messages={'c1': '优先错信息1', 'c2': '优先错信息2', 'c3': '优先错信息3'}, max_length=32, validators=[django.core.validators.RegexValidator(code='c1', message='错误了', regex='root_\\d+'), django.core.validators.RegexValidator(code='c2', message='又错误了', regex='root_112233\\d+'), django.core.validators.EmailValidator(code='c3', message='又错误了')]),
            preserve_default=False,
        ),
    ]
