# Generated by Django 2.0.6 on 2018-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=True, to='app01.Boy')),
                ('gid', models.ForeignKey(on_delete=True, to='app01.Girl')),
            ],
        ),
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(through='app01.Love', to='app01.Girl'),
        ),
        migrations.AlterUniqueTogether(
            name='love',
            unique_together={('bid', 'gid')},
        ),
    ]
