# Generated by Django 2.0.6 on 2018-07-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180715_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together={('b', 'g')},
        ),
    ]
