# Generated by Django 2.0.6 on 2018-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180715_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(to='app01.Girl'),
        ),
    ]
