# Generated by Django 2.0.6 on 2018-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_boy_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=True, to='app01.Boy')),
                ('g', models.ForeignKey(on_delete=True, to='app01.Girl')),
            ],
        ),
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(through='app01.Love', to='app01.Girl'),
        ),
        migrations.AlterUniqueTogether(
            name='love',
            unique_together={('b', 'g')},
        ),
    ]
