# Generated by Django 2.0.6 on 2018-07-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180715_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boy',
            name='m',
        ),
        migrations.AlterUniqueTogether(
            name='love',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='love',
            name='b',
        ),
        migrations.RemoveField(
            model_name='love',
            name='g',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ut',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, default='1111', help_text='熬枯受淡发送到发送到', max_length=254, null=True, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='ddddddddddd', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Boy',
        ),
        migrations.DeleteModel(
            name='Girl',
        ),
        migrations.DeleteModel(
            name='Love',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
